"""test

Revision ID: 34fbb5ec41cc
Revises: d1710aa3b2aa
Create Date: 2023-07-24 01:50:54.613719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fbb5ec41cc'
down_revision = 'd1710aa3b2aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
