"""test

Revision ID: 425b83a12d76
Revises: bda0b37b1618
Create Date: 2023-07-24 01:53:24.033641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425b83a12d76'
down_revision = 'bda0b37b1618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
