"""test

Revision ID: 456eb58a84c5
Revises: 425b83a12d76
Create Date: 2023-07-24 01:57:28.457083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456eb58a84c5'
down_revision = '425b83a12d76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
