"""addifeld

Revision ID: a8bf1178ccee
Revises: 0845fb5b17bd
Create Date: 2023-07-15 22:15:22.142085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bf1178ccee'
down_revision = '0845fb5b17bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
