"""Your migration message

Revision ID: ae3077c75401
Revises: e750dab5e90e
Create Date: 2023-07-15 22:30:58.206440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3077c75401'
down_revision = 'e750dab5e90e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
