"""test

Revision ID: bda0b37b1618
Revises: 34fbb5ec41cc
Create Date: 2023-07-24 01:52:23.468778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda0b37b1618'
down_revision = '34fbb5ec41cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
