"""test

Revision ID: d1710aa3b2aa
Revises: 6c244afd6a12
Create Date: 2023-07-24 01:40:57.427586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1710aa3b2aa'
down_revision = '6c244afd6a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    op.add_column('convos', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('convos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'convos', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'convos', 'chats', ['chat_id'], ['id'])
    op.add_column('messages', sa.Column('convo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'convos', ['convo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'convo_id')
    op.drop_constraint(None, 'convos', type_='foreignkey')
    op.drop_constraint(None, 'convos', type_='foreignkey')
    op.drop_column('convos', 'user_id')
    op.drop_column('convos', 'chat_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'user_id')
    # ### end Alembic commands ###
